### ISSUE TITLE
QUIT_APP command panics

### ISSUE THREAD

**Issue by xliiv** [xi-editor/druid#505]
Running
```rust
use druid::widget::{Button, Flex};
use druid::{AppLauncher, Widget, WindowDesc};

fn main () {
    let window = WindowDesc::new(build_widget);
    AppLauncher::with_window(window)
        .use_simple_logger()
        .launch(0_u32)
        .expect("launch failed");
}

fn build_widget() -> impl Widget<u32> {
    Flex::column()
        .with_child(
            Button::new(
                "Quit",
                |evt_ctx , data: _, _env| {
                    dbg!(&data);
                    let command = druid::Command::new(druid::commands::QUIT_APP, evt_ctx.window_id());
                    evt_ctx.submit_command(command, None);
                },
            ),
            1.0,
        )
}
```
gives
```
> env RUST_BACKTRACE=1 cargo run --example quit
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/quit`
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
Activated application
[druid/examples/quit.rs:18] &data = 0
thread 'main' panicked at 'Attempted to quit a GTK main loop when none is running.', /home/xliiv/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.8.0/src/rt.rs:127:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12: gtk::rt::main_quit
             at /home/xliiv/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.8.0/src/rt.rs:127
  13: druid_shell::platform::gtk::application::Application::quit::{{closure}}
             at druid-shell/src/platform/gtk/application.rs:39
  14: druid_shell::platform::gtk::runloop::with_application::{{closure}}
             at druid-shell/src/platform/gtk/runloop.rs:88
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  16: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  17: druid_shell::platform::gtk::runloop::with_application
             at druid-shell/src/platform/gtk/runloop.rs:83
  18: druid_shell::platform::gtk::application::Application::quit
             at druid-shell/src/platform/gtk/application.rs:32
  19: druid_shell::application::Application::quit
             at druid-shell/src/application.rs:33
  20: druid::win_handler::DruidHandler<T>::quit
             at ./druid/src/win_handler.rs:742
  21: druid::win_handler::DruidHandler<T>::handle_cmd
             at ./druid/src/win_handler.rs:653
  22: druid::win_handler::DruidHandler<T>::process_commands
             at ./druid/src/win_handler.rs:609
  23: druid::win_handler::DruidHandler<T>::do_event
             at ./druid/src/win_handler.rs:600
  24: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::mouse_up
             at ./druid/src/win_handler.rs:790
  25: druid_shell::platform::gtk::window::WindowBuilder::build::{{closure}}
             at druid-shell/src/platform/gtk/window.rs:280
  26: <O as gtk::auto::widget::WidgetExt>::connect_button_release_event::button_release_event_trampoline
             at /home/xliiv/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.8.0/src/auto/widget.rs:3096
  27: <unknown>
  28: g_closure_invoke
  29: <unknown>
  30: g_signal_emit_valist
  31: g_signal_emit
  32: <unknown>
  33: <unknown>
  34: gtk_main_do_event
  35: <unknown>
  36: <unknown>
  37: g_main_context_dispatch
  38: <unknown>
  39: g_main_context_iteration
  40: g_application_run
  41: <O as gio::application::ApplicationExtManual>::run
             at /home/xliiv/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.8.0/src/application.rs:23
  42: druid_shell::platform::gtk::runloop::RunLoop::run::{{closure}}
             at druid-shell/src/platform/gtk/runloop.rs:69
  43: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  44: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  45: druid_shell::platform::gtk::runloop::RunLoop::run
             at druid-shell/src/platform/gtk/runloop.rs:68
  46: druid_shell::runloop::RunLoop::run
             at druid-shell/src/runloop.rs:36
  47: druid::app::AppLauncher<T>::launch
             at ./druid/src/app.rs:130
  48: quit::main
             at druid/examples/quit.rs:6
  49: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  50: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  51: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  52: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  53: std::panicking::try
             at src/libstd/panicking.rs:265
  54: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  55: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  56: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  57: main
  58: __libc_start_main
  59: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

I'm using `master` branch
```
> git log -n1
commit 73d94b7feaf913e5c4c901501cb576b9f388de15 (HEAD -> master, origin/master, origin/HEAD)
Merge: c8a8cba dfe15ed
Author: Paul Miller <paul@pauljmiller.com>
Date:   Sat Feb 1 10:43:14 2020 -0800

    Merge pull request #298 from futurepaul/editable-text-trait

    EditableText trait
> dnf list --installed|rg "(gtk3-devel|glib2-devel)"
glib2-devel.x86_64                                 2.62.3-1.fc31                        @updates                                          
gtk3-devel.x86_64                                  3.24.13-1.fc31                       @updates
```

**Comment by cmyr** [comment]
This is with the gtk backend?

**Comment by xliiv** [comment]
> This is with the gtk backend?

correct

**Comment by cmyr** [comment]
realistically I'm not going to look at this for a little bit, but it should be possible to dig in, there seems to be some useful stuff in that crash log. Where does "Attempted to quit a GTK main loop when none is running." come from?

**Comment by xliiv** [comment]
> Where does "Attempted to quit a GTK main loop when none is running." come from?

It's here

**Comment by Dmitry-Borodin** [comment]
Because gtk_sys::gtk_main_level() always 0
Even during initialization 
```
    gtk::init().expect("GTK initialization failed");
    gtk::main_quit();
```
will cause the same crash. I will try to find out the reason.
