### ISSUE TITLE
context menu pop up causes crash

### ISSUE THREAD

**Issue by kindlychung** [xi-editor/druid#735]
Right click on the multiwin example gives me this:

```
cargo run --example multiwin
   Compiling druid v0.5.0 (/home/kaiyin/rustProjects/druid/druid)
    Finished dev [unoptimized + debuginfo] target(s) in 3.80s
     Running `/home/kaiyin/rustProjects/druid/target/debug/examples/multiwin`
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
DEBUG [druid::localization] available locales [en-US, de-DE, fr-CA], current en-US
DEBUG [druid::localization] resolved: [en-US]
WARN  [druid::menu] MenuDesc::platform_default is not implemented for this platform.
INFO  [multiwin] Window added, id: WindowId(1)
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/cell.rs:878:9
stack backtrace:
   0:     0x560fa3665c64 - <unknown>
   1:     0x560fa36852bc - <unknown>
   2:     0x560fa3663a93 - <unknown>
   3:     0x560fa3668295 - <unknown>
   4:     0x560fa3667fe2 - <unknown>
   5:     0x560fa36688f2 - <unknown>
   6:     0x560fa36684db - <unknown>
   7:     0x560fa3683c81 - <unknown>
   8:     0x560fa3683aa3 - <unknown>
   9:     0x560fa3651550 - <unknown>
  10:     0x7fc689bcb7ff - <unknown>
  11:     0x7fc68931b936 - <unknown>
  12:     0x7fc689337dcb - g_signal_emit_valist
  13:     0x7fc6893389b3 - g_signal_emit
  14:     0x7fc689b75e53 - <unknown>
  15:     0x7fc689b760ec - <unknown>
  16:     0x7fc689b7ca27 - <unknown>
  17:     0x7fc689a31b88 - <unknown>
  18:     0x7fc689a31f49 - <unknown>
  19:     0x7fc689915639 - <unknown>
  20:     0x7fc689a31e60 - <unknown>
  21:     0x7fc689b8bf19 - <unknown>
  22:     0x7fc689a31e60 - <unknown>
  23:     0x7fc689a32008 - <unknown>
  24:     0x7fc689a3b233 - <unknown>
  25:     0x7fc689a3b755 - gtk_menu_popup
  26:     0x560fa364d8f7 - <unknown>
  27:     0x560fa364b250 - <unknown>
  28:     0x560fa361f6ba - <unknown>
  29:     0x560fa361ca4a - <unknown>
  30:     0x560fa361dafa - <unknown>
  31:     0x560fa361e081 - <unknown>
  32:     0x560fa361df0c - <unknown>
  33:     0x560fa361e9cf - <unknown>
  34:     0x560fa36511c0 - <unknown>
  35:     0x7fc689bcb70b - <unknown>
  36:     0x7fc68931b6e2 - g_closure_invoke
  37:     0x7fc68932f544 - <unknown>
  38:     0x7fc68933799e - g_signal_emit_valist
  39:     0x7fc6893389b3 - g_signal_emit
  40:     0x7fc689b75e53 - <unknown>
  41:     0x7fc689a319d8 - <unknown>
  42:     0x7fc689a33c2b - gtk_main_do_event
  43:     0x7fc68971df19 - <unknown>
  44:     0x7fc689750ff6 - <unknown>
  45:     0x7fc68923084d - g_main_context_dispatch
  46:     0x7fc689230ad0 - <unknown>
  47:     0x7fc689230b73 - g_main_context_iteration
  48:     0x7fc689443b05 - g_application_run
  49:     0x560fa364e96c - <unknown>
  50:     0x560fa364af76 - <unknown>
  51:     0x560fa364a996 - <unknown>
  52:     0x560fa3615471 - <unknown>
  53:     0x560fa3619853 - <unknown>
  54:     0x560fa3614340 - <unknown>
  55:     0x560fa3668dbf - <unknown>
  56:     0x560fa361a39c - <unknown>
  57:     0x7fc688fd01e3 - __libc_start_main
  58:     0x560fa361018e - <unknown>
  59:                0x0 - <unknown>
```

**Comment by cmyr** [comment]
This is an issue in the gtk backend.

**Comment by sjoshid** [comment]
Here's a more detailed stacktrace. 
```
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/cell.rs:878:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: core::result::Result<T,E>::expect
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:991
  15: core::cell::RefCell<T>::borrow_mut
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/cell.rs:878
  16: druid_shell::platform::gtk::window::WindowBuilder::build::{{closure}}
             at druid-shell/src/platform/gtk/window.rs:343
  17: <O as gtk::auto::widget::WidgetExt>::connect_leave_notify_event::leave_notify_event_trampoline
             at /home/sugs/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.8.0/src/auto/widget.rs:4154
  18: <unknown>
  19: <unknown>
  20: g_signal_emit_valist
  21: g_signal_emit
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: gtk_menu_popup
  34: <O as gtk::menu::GtkMenuExtManual>::popup_easy
             at /home/sugs/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.8.0/src/menu.rs:79
  35: druid_shell::platform::gtk::window::WindowHandle::show_context_menu
             at druid-shell/src/platform/gtk/window.rs:606
  36: druid_shell::window::WindowHandle::show_context_menu
             at druid-shell/src/window.rs:187
  37: druid::window::Window<T>::show_context_menu
             at ./druid/src/window.rs:93
  38: druid::win_handler::Inner<T>::show_context_menu
             at ./druid/src/win_handler.rs:354
  39: druid::win_handler::Inner<T>::dispatch_cmd
             at ./druid/src/win_handler.rs:291
  40: druid::win_handler::AppState<T>::handle_cmd
             at ./druid/src/win_handler.rs:514
  41: druid::win_handler::AppState<T>::process_commands
             at ./druid/src/win_handler.rs:461
  42: druid::win_handler::AppState<T>::do_window_event
             at ./druid/src/win_handler.rs:433
  43: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::mouse_down
             at ./druid/src/win_handler.rs:628
  44: druid_shell::platform::gtk::window::WindowBuilder::build::{{closure}}
             at druid-shell/src/platform/gtk/window.rs:283
  45: <O as gtk::auto::widget::WidgetExt>::connect_button_press_event::button_press_event_trampoline
             at /home/sugs/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.8.0/src/auto/widget.rs:3061
  46: <unknown>
  47: g_closure_invoke
  48: <unknown>
  49: g_signal_emit_valist
  50: g_signal_emit
  51: <unknown>
  52: <unknown>
  53: gtk_main_do_event
  54: <unknown>
  55: <unknown>
  56: g_main_context_dispatch
  57: <unknown>
  58: g_main_context_iteration
  59: g_application_run
  60: <O as gio::application::ApplicationExtManual>::run
             at /home/sugs/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.8.0/src/application.rs:23
  61: druid_shell::platform::gtk::application::Application::run::{{closure}}
             at druid-shell/src/platform/gtk/application.rs:67
  62: std::thread::local::LocalKey<T>::try_with
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/local.rs:262
  63: std::thread::local::LocalKey<T>::with
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/local.rs:239
  64: druid_shell::platform::gtk::application::Application::run
             at druid-shell/src/platform/gtk/application.rs:66
  65: druid_shell::application::Application::run
             at druid-shell/src/application.rs:53
  66: druid::app::AppLauncher<T>::launch
             at ./druid/src/app.rs:127
  67: multiwin::main
             at druid/examples/multiwin.rs:43
  68: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  69: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  70: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  71: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  72: std::panicking::try
             at src/libstd/panicking.rs:281
  73: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  74: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  75: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  76: main
  77: __libc_start_main
  78: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101

```

**Comment by Dmitry-Borodin** [comment]
This looks similar to #571 and probably need architecture changes to fix

**Comment by Dmitry-Borodin** [comment]
Don't need to do context menu. Right click to window crashing it.
