### ISSUE TITLE
Panic when clicking into empty textbox

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/druid#958]
Clicking into an empty textbox results in druid crashing on macOS. This issue might be a problem in `piet` itself, it seems to be related to the newly added coregraphics support.

The stacktrace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/anna/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-coregraphics-0.1.0/src/text.rs:179:26
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: core::option::Option<T>::unwrap
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/macros/mod.rs:10
  15: <piet_coregraphics::text::CoreGraphicsTextLayout as piet::text::TextLayout>::hit_test_point
             at /Users/anna/.cargo/registry/src/github.com-1ecc6299db9ec823/piet-coregraphics-0.1.0/src/text.rs:179
  16: druid::widget::textbox::TextBox::offset_for_point
             at druid/src/widget/textbox.rs:185
  17: <druid::widget::textbox::TextBox as druid::widget::widget::Widget<alloc::string::String>>::event
             at druid/src/widget/textbox.rs:247
  18: <druid::lens::lens::LensWrap<U,L,W> as druid::widget::widget::Widget<T>>::event::{{closure}}
             at ./druid/src/lens/lens.rs:221
  19: flex::<impl druid::lens::lens::Lens<flex::DemoState,alloc::string::String> for flex::demo_state_derived_lenses::input_text>::with_mut
             at druid/examples/flex.rs:34
  20: <druid::lens::lens::LensWrap<U,L,W> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/lens/lens.rs:220
  21: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  22: druid::core::WidgetPod<T,W>::event
             at ./druid/src/core.rs:691
  23: <druid::widget::flex::Flex<T> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/flex.rs:520
  24: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  25: druid::core::WidgetPod<T,W>::event
             at ./druid/src/core.rs:691
  26: <druid::widget::container::Container<T> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/container.rs:102
  27: <druid::lens::lens::LensWrap<U,L,W> as druid::widget::widget::Widget<T>>::event::{{closure}}
             at ./druid/src/lens/lens.rs:221
  28: flex::<impl druid::lens::lens::Lens<flex::AppState,flex::DemoState> for flex::app_state_derived_lenses::demo_state>::with_mut
             at druid/examples/flex.rs:28
  29: <druid::lens::lens::LensWrap<U,L,W> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/lens/lens.rs:220
  30: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  31: <druid::widget::sized_box::SizedBox<T> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/sized_box.rs:135
  32: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  33: <flex::Rebuilder as druid::widget::widget::Widget<flex::AppState>>::event
             at druid/examples/flex.rs:86
  34: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  35: druid::core::WidgetPod<T,W>::event
             at ./druid/src/core.rs:691
  36: <druid::widget::flex::Flex<T> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/flex.rs:520
  37: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  38: druid::core::WidgetPod<T,W>::event
             at ./druid/src/core.rs:691
  39: <druid::widget::padding::Padding<T> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/padding.rs:77
  40: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  41: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::event
             at ./druid/src/widget/widget.rs:222
  42: druid::core::WidgetPod<T,W>::event
             at ./druid/src/core.rs:691
  43: druid::window::Window<T>::event
             at ./druid/src/window.rs:213
  44: druid::win_handler::Inner<T>::do_window_event
             at ./druid/src/win_handler.rs:366
  45: druid::win_handler::AppState<T>::do_window_event
             at ./druid/src/win_handler.rs:463
  46: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::mouse_down
             at ./druid/src/win_handler.rs:663
  47: druid_shell::platform::mac::window::mouse_down
             at druid-shell/src/platform/mac/window.rs:459
  48: druid_shell::platform::mac::window::mouse_down_left
             at druid-shell/src/platform/mac/window.rs:437
  49: <unknown>
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <() as objc::message::MessageArguments>::invoke
             at /Users/anna/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  55: objc::message::platform::send_unverified
             at /Users/anna/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  56: objc::message::send_message
             at /Users/anna/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  57: <*mut objc::runtime::Object as cocoa::appkit::NSApplication>::run
             at /Users/anna/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.20.0/src/appkit.rs:438
  58: druid_shell::platform::mac::application::Application::run
             at druid-shell/src/platform/mac/application.rs:77
  59: druid_shell::application::Application::run
             at druid-shell/src/application.rs:156
  60: druid::app::AppLauncher<T>::launch
             at ./druid/src/app.rs:138
  61: flex::main
             at druid/examples/flex.rs:328
  62: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  63: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  64: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  65: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  66: std::panicking::try
             at src/libstd/panicking.rs:281
  67: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  68: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  69: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  70: <flex::FlexType as core::clone::Clone>::clone
```

**Comment by cmyr** [comment]
oops this will be a bug somewhere in piet hit-testing, I bet; we just landed the piet CoreGraphics backend, so not unreasonable we'll find some things like this.
